### ISSUE TITLE
Help me add mobile responsiveness

### ISSUE THREAD

**Issue by Boby900** [Boby900/patilkaki#1]
my  `/becoming` page doesn't have responsiveness, if you could help me fix that, it would be great.

![Screenshot (288)](https://github.com/Boby900/patilkaki/assets/111265239/cfcf6266-7908-4d73-aea7-4efed91f2409)

**Comment by AnukratiMehta** [comment]
@Boby900 

Hello, I would like to work on this. Please assign it.

**Comment by Boby900** [comment]
> @Boby900
> 
> Hello, I would like to work on this. Please assign it.

Hey @AnukratiMehta I have assigned this to you

**Comment by Boby900** [comment]
@AnukratiMehta  thanks a lot now it's looking better
