### ISSUE TITLE
Help me add responsiveness

### ISSUE THREAD

**Issue by Boby900** [Boby900/patilkaki#3]
If you could help me add mobile responsiveness, that would be so helpful

![Screenshot (291)](https://github.com/Boby900/patilkaki/assets/111265239/397da102-d07d-4e2d-afdb-929e94a56a24)

**Comment by Amrani-Farouk-Hossam-Eddine** [comment]
Hi, i'm interesting in this issue, so i want to work on it if there is no one working on it currently ?

**Comment by Boby900** [comment]
> Hi, i'm interesting in this issue, so i want to work on it if there is no one working on it currently ?

yep, right now no one working on it so you can work on it @Amrani-Farouk-Hossam-Eddine
